name: wma-4

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend
    develop:
      watch:
        - path: ./frontend/src
          action: sync
          target: ./app/src
        - path: ./frontend/package.json
          action: rebuild

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3001:3001
    env_file: ./backend/.env
    depends_on:
      - db
    develop:
      watch:
        - path: ./backend/src
          action: sync
          target: ./app/src
        - path: ./backend/package.json
          action: rebuild

  db:
    container_name: db
    image: postgres:alpine
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data

volumes:
  pgdata:
